export enum MediaFunction {
	TASK_IMAGE ="TASK_IMAGE",
    LIVEWIRE_MEDIA = "LIVEWIRE_MEDIA",
    USER_PROFILE_IMAGE = "USER_PROFILE_IMAGE",
    BROADCAST_IMAGE = "BROADCAST_IMAGE",
    GENERAL_UNKNOWN = "GENERAL_UNKNOWN"
}
