version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
    steps:
      - checkout
      - run: echo "Initiating build"
      # - run:
      #     name: Get Webpack
      #     command: |
      #       sudo npm i -g webpack
      #       sudo npm i -g webpack-dev-server
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules  
      # - run: 
      #     name: Build server and browser
      #     command: npm run build:uni
      # - save_cache:
      #     key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      #     paths:
      #       - dist-server
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Build Docker image
      #     command: docker build -f Dockerfile -t grassroot-frontend:latest-$CIRCLE_BRANCH .
      - run:
          name: Install AWS CLI and log in
          command: |
            sudo apt-get update && sudo apt-get install python && sudo apt-get install python-pip
            pip install awscli --upgrade --user
            eval $(aws ecr get-login --no-include-email --region eu-west-1)
      - run:
          name: Tag and upload image to ECR          
          command: |
            docker tag grassroot-frontend:latest-$CIRCLE_BRANCH ${ECR_URL}/grassroot-frontend:latest-$CIRCLE_BRANCH
            docker push ${ECR_URL}/grassroot-frontend:latest-$CIRCLE_BRANCH