export enum TodoType {

  INFORMATION_REQUIRED = "INFORMATION_REQUIRED",
  VALIDATION_REQUIRED = "VALIDATION_REQUIRED",
  ACTION_REQUIRED = "ACTION_REQUIRED",
  VOLUNTEERS_NEEDED = "VOLUNTEERS_NEEDED"
}
